# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Web Accessibility Initiative (WAI)"
email: gl041188@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Website of the World Wide Web Consortium’s Web Accessibility Initiative.
baseurl: "/wai-about-wai" # the subpath of your site, e.g. /blog
url: "https://w3c.github.io" # the base hostname & protocol for your site
twitter:
  username: w3c_wai
author: w3c_wai
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"

# Build settings
markdown: kramdown
kramwdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: w3c/wai-about-wai

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

remote_theme: w3c/wai-website-theme

collections:
  about:
    area: "About WAI"
    name: "About WAI"
    shortname: "About WAI"
    # icon: "book" # TODO
    repostitory: w3c/wai-about-wai
    output: true
    acknowledgements: false
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: "_about"
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-remote-theme
  - wai-website-plugin
